app:
  access-type: ORM # или SQL
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  db:
      batch-size: 1000 # Размер батча
  scheduler:
    delay-ms: 30000 # Интервал между проверками (30 секунд)
    num-threads: 4 # Количество потоков

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  liquibase:
    enabled: false
#    change-log: ./migrations/master.xml
#    url: ${spring.datasource.url}
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
