app:
  message-transport: HTTP # Kafka или HTTP
  access-type: ORM # или SQL
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  db:
      batch-size: 1000 # Размер батча
  scheduler:
    delay-ms: 30000 # Интервал между проверками (30 секунд)
    num-threads: 4 # Количество потоков

spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: scrapper-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "backend.academy.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j.ratelimiter:
  instances:
    linkControllerRateLimiter:
      limitForPeriod: 10 # Максимальное количество запросов за период
      limitRefreshPeriod: 1s # Период обновления лимита
      timeoutDuration: 0 # Таймаут, если лимит исчерпан

http:
  timeout:
    connect: 5000 # Таймаут подключения в миллисекундах
    read: 5000    # Таймаут чтения в миллисекундах
  retry:
    max-attempts: 3                   # Максимальное количество попыток (включая первую)
    backoff-ms: 1000                  # Задержка между попытками (в миллисекундах)
    retryable-status-codes: 500,502,503,504

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

kafka:
  topic:
    chat-register: chat-register
    chat-delete: chat-delete
    link-add: link-add
    link-remove: link-remove
    link-updates: link-updates
    get-links-request: get-links-request
    response-topic: kafka-response-topic
    add-tags-request: add-tags-request
    remove-tag-request: remove-tag-request
    get-tags-for-link-request: get-tags-for-link-request
    get-links-by-tag-request: get-links-by-tag-request
    dead-letter-queue: dlq-updates


---
# Профиль для SQL
spring:
  config:
    activate:
      on-profile: sql-test
app:
  access-type: SQL

---
# Профиль для ORM
spring:
  config:
    activate:
      on-profile: orm-test
app:
  access-type: ORM

