app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  message-transport: HTTP # Kafka или HTTP
  digest: "0 0 10 * * ?" # Каждый день в 10:00

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bot-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "backend.academy.model"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

resilience4j.ratelimiter:
  instances:
    updateControllerRateLimiter:
      limitForPeriod: 10 # Максимальное количество запросов за период
      limitRefreshPeriod: 1s # Период обновления лимита
      timeoutDuration: 0 # Таймаут, если лимит исчерпан

http:
  timeout:
    connect: 5000 # Таймаут подключения в миллисекундах
    read: 5000    # Таймаут чтения в миллисекундах
  retry:
    max-attempts: 3                   # Максимальное количество попыток (включая первую)
    backoff-ms: 1000                  # Задержка между попытками (в миллисекундах)
    retryable-status-codes: 500,502,503,504

resilience4j.circuitbreaker:
  instances:
    scrapperClient: # Имя инстанса CB
      slidingWindowSize: 3            # Размер окна для расчета статистики ошибок
      failureRateThreshold: 50        # Порог ошибок (в процентах), при котором CB переходит в OPEN
      waitDurationInOpenState: 5s     # Время, в течение которого CB остается в состоянии OPEN
      automaticTransitionFromOpenToHalfOpenEnabled: true # Автоматический переход из OPEN в HALF_OPEN
      recordExceptions: org.springframework.web.client.HttpServerErrorException # Только 5xx
      ignoreExceptions: org.springframework.web.client.HttpClientErrorException # Игнорировать 4xx

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

kafka:
  topic:
    chat-register: chat-register
    chat-delete: chat-delete
    link-add: link-add
    link-remove: link-remove
    link-updates: link-updates
    get-links-request: get-links-request
    response-topic: kafka-response-topic
    add-tags-request: add-tags-request
    remove-tag-request: remove-tag-request
    get-tags-for-link-request: get-tags-for-link-request
    get-links-by-tag-request: get-links-by-tag-request
    dead-letter-queue: dlq-updates
    health-check-topic: health-check-topic

---
spring:
  config:
    activate:
      on-profile: test
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      port: 6379
      host: localhost
